### ISSUE TITLE
Classe Car_.java

### ISSUE THREAD

**Issue by jrzielinski** [adminfaces/admin-starter-persistence#1]
Você poderia disponibilizar essa classe. Não consegui achar dentro do projeto, apenas referências a ela. E parabéns pelo trabalho, excelente código.

**Comment by rmpestano** [comment]
@jrzielinski, as classes com sulfixo `_` são geradas durante o build maven (fase `package` do build) por [esse plugin](https://github.com/adminfaces/admin-starter-persistence/blob/master/pom.xml#L197).  A idéia é que você possa referenciar nomes de atributos de uma classe de uma maneira type safe (sem usar Strings) para facilitar refatoração e evitar erros de digitação. 

O nome desse processo é `geração de meta modelo de classes` (metamodel generation)

Existem outras maneiras de se gerar o meta modelo de classes Java, veja alguns exemplos aqui: https://docs.jboss.org/hibernate/orm/5.0/topical/html/metamodelgen/MetamodelGenerator.html#_usage_within_the_ide

Espero que tenha ficado claro.

**Comment by jrzielinski** [comment]
Obrigado,... Ficou bem claro.
