### ISSUE TITLE
Car_ class not available

### ISSUE THREAD

**Issue by beautifulnature** [adminfaces/admin-starter-persistence#2]
import com.github.adminfaces.starter.model.Car_ not available which referenced in com.github.adminfaces.starter.service.CarService

package com.github.adminfaces.starter.service;

import com.github.adminfaces.persistence.model.Filter;
import com.github.adminfaces.persistence.service.CrudService;
import com.github.adminfaces.starter.model.Car;
**import com.github.adminfaces.starter.model.Car_;**
import com.github.adminfaces.template.exception.BusinessException;
import org.apache.deltaspike.data.api.criteria.Criteria;

import javax.ejb.Stateless;
import javax.inject.Inject;
import javax.persistence.metamodel.SingularAttribute;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.List;

import static com.github.adminfaces.template.util.Assert.has;

/**
 * @author rmpestano
 */
@Stateless
public class CarService extends CrudService<Car, Integer> implements Serializable

**Comment by rmpestano** [comment]
Hi, can you look If It is related to this issue: https://github.com/adminfaces/admin-starter-persistence/issues/1#issuecomment-358143267

**Comment by rmpestano** [comment]
Issue #1 is in PT_BR but what It says is basically that entities with underline sufix are generated at build time so after doing a mvn package should generate It. Also check the links in #1, they show how to integrante this process into IDE.

Hope It helps

**Comment by beautifulnature** [comment]
thank you, its working.
